vich_uploader:
    db_driver: orm


    mappings:
        file:
            uri_prefix: '%app.path.file%'
            upload_destination: '%kernel.project_dir%/public%app.path.file%'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
